services:
  back:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ${PUBLIC_UPLOAD_FOLDER}:/public-upload
      - ${PRIVATE_UPLOAD_FOLDER}:/private-upload
    environment:
      - ${PUBLIC_UPLOAD_FOLDER}:${PUBLIC_UPLOAD_FOLDER}
      - ${PRIVATE_UPLOAD_FOLDER}:${PRIVATE_UPLOAD_FOLDER}

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - "3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data:




#services:
#  static:
#    image: nginx:latest
#    ports:
#      - "81:80"
#    volumes:
#      - ${PUBLIC_UPLOAD_FOLDER}:/usr/share/nginx/html/images
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    env_file:
#      - .env
#      - .local.env
#    environment:
#      - PUBLIC_UPLOAD_FOLDER=${PUBLIC_UPLOAD_FOLDER}
